sdhdevicetype: TCP
sdhdevicestring: 172.31.1.154
sdhport: 23
baudrate: 100000
joint_names: ['schunk_right_knuckle_joint', 'schunk_right_thumb_2_joint', 'schunk_right_thumb_3_joint', 'schunk_right_finger_12_joint', 'schunk_right_finger_13_joint', 'schunk_right_finger_22_joint', 'schunk_right_finger_23_joint']
OperationMode: position
frequency: 100
